-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 28, 2021 at 03:38 PM
-- Server version: 10.4.20-MariaDB
-- PHP Version: 8.0.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `blog`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `id` int(11) NOT NULL,
  `category` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `category`) VALUES
(1, 'Mountain area'),
(2, 'National parks'),
(3, 'Historical place'),
(4, 'Famous temple');

-- --------------------------------------------------------

--
-- Table structure for table `comments`
--

CREATE TABLE `comments` (
  `id` int(11) NOT NULL,
  `responseTo` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `message` text NOT NULL,
  `content` int(11) NOT NULL,
  `added_on` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `comments`
--

INSERT INTO `comments` (`id`, `responseTo`, `name`, `message`, `content`, `added_on`) VALUES
(185, 0, 'kapil', 'nice place', 2, '2021-09-27 12:16:11'),
(198, 0, 'kapil', 'cool application', 3, '2021-09-28 15:36:48');

-- --------------------------------------------------------

--
-- Table structure for table `contents`
--

CREATE TABLE `contents` (
  `id` int(11) NOT NULL,
  `image` varchar(100) NOT NULL,
  `title` varchar(100) NOT NULL,
  `place` varchar(100) NOT NULL,
  `detail` text NOT NULL,
  `category` int(11) NOT NULL,
  `popular` int(11) NOT NULL,
  `date` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `contents`
--

INSERT INTO `contents` (`id`, `image`, `title`, `place`, `detail`, `category`, `popular`, `date`) VALUES
(1, 'travel1.webp', 'Mumbai card', 'Mumbai', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 3, 0, '2021-08-25 07:31:43'),
(2, 'travel2.webp', 'Haji Ali Dargah', 'Mumbai', 'The Haji Ali Dargah is a mosque and dargah or the monument of Pir Haji Ali Shah Bukhari located on an islet off the coast of Worli in the southern Mumbai. An exquisite example of Indo-Islamic Architecture, associated with legends about doomed lovers, the dargah contains the tomb of Haji Ali Shah Bukhari. Bukhari was a Sufi saint and a wealthy merchant from Uzbekistan. Near the heart of the city proper, the dargah is one of the most recognisable landmarks of Mumbai.', 4, 0, '2021-08-25 07:31:43'),
(3, 'travel3.jpg', 'Moti masjid', 'Bhopal', 'Built by Sikander Begum in 1860, it is an important historical landmark in Bhopal. Located at Peer Gate, the red stone and marble mosque is unique. It has two dark red towers with golden spikes and the mosque proper has a sparkling white facade hence the term \' Moti Masjid\' or the \' Pearl Mosque\'.', 4, 0, '2021-08-25 07:42:42'),
(4, 'travel4.jpg\r\n', 'India gate', 'Delhi', 'Built by Sikander Begum in 1860, it is an important historical landmark in Bhopal. Located at Peer Gate, the red stone and marble mosque is unique. It has two dark red towers with golden spikes and the mosque proper has a sparkling white facade hence the term \' Moti Masjid\' or the \' Pearl Mosque\'.', 3, 0, '2021-08-25 07:42:42'),
(5, 'travel5.jpg', 'Jaldapara National Park', 'West bangle', 'Jaldapara National Park (Pron: ˌʤʌldəˈpɑ:rə) is a national park situated at the foothills of the Eastern Himalayas in Alipurduar District of northern West Bengal and on the banks of the Torsa River. Jaldapara is situated at an altitude of 61 m and is spread across 216.51 km2 (83.59 sq mi) of vast grassland with patches of riverine forests.[1] It was declared a sanctuary in 1941 for protection of its great variety flora and fauna. Today, it has the largest population of the Indian one horned rhinoceros in the state, an animal threatened with extinction,[2] and is a Habitat management area (Category IV).[3] The nearby Chilapata Forests is an elephant corridor between Jaldapara and the Buxa Tiger Reserve[4] Near by is the Gorumara National Park, known for its population of Indian rhinoceros. The Office of the Divisional Forest Officer, Jaldapara Office is situated at Nilkuthi, Cooch Behar and the Office of the Assistant Wildlife Warden is situated at the heart point of the National Park i.e Madarihat.', 2, 0, '2021-08-25 07:54:55'),
(6, 'travel6.jpg', 'udaipur', 'Rajasthan', 'Jagdish Temple is a large Hindu temple in the middle of Udaipur in Rajasthan, just outside the royal palace. It has been in continuous worship since 1651. A big tourist attraction, the temple was originally called the temple of Jagannath Rai but is now called Jagdish-ji. It is a major monument in Udaipur.', 3, 0, '2021-08-25 07:54:55'),
(7, 'travel7.png', 'Amritshar', 'Punjab', 'Amritsar is a city in the northwestern Indian state of Punjab, 28 kilometers from the border with Pakistan. At the center of its walled old town, the gilded Golden Temple (Harmandir Sahib) is the holiest gurdwara (religious complex) of the Sikh religion. It’s at the end of a causeway, surrounded by the sacred Amrit Sarovar tank (lake), where pilgrims bathe.', 4, 0, '2021-08-25 08:07:24'),
(8, 'travel8.jpg', 'Kochi', 'kerala', 'Amritsar is a city in the northwestern Indian state of Punjab, 28 kilometers from the border with Pakistan. At the center of its walled old town, the gilded Golden Temple (Harmandir Sahib) is the holiest gurdwara (religious complex) of the Sikh religion. It’s at the end of a causeway, surrounded by the sacred Amrit Sarovar tank (lake), where pilgrims bathe.', 1, 0, '2021-08-25 08:07:24'),
(9, 'travel9.jpg', 'Taj mahal', 'Agra', 'Perhaps India\'s most recognizable building, the Taj Mahal is also the world\'s most famous testimony to the power of love. Named after Mumtaz Mahal, the favorite wife of Emperor Shah Jahan, this most beautiful of mausoleums was begun upon her death in 1631 and took 20,000 workmen until 1648 to complete.\r\n\r\nIncorporating many elements of Islamic design including arches, minarets, an onion-shaped dome, and black calligraphy inlaid around the entrance, the Taj Mahal is largely constructed of white marble decorated with delicate inlaid floral patterns and precious and semi-precious stones such as jade, lapis lazuli, diamonds, and mother of pearl.', 3, 1, '2021-08-25 11:14:10'),
(10, 'travel10.jpg', 'Red Ford', 'Delhi', 'Perhaps India\'s most recognizable building, the Taj Mahal is also the world\'s most famous testimony to the power of love. Named after Mumtaz Mahal, the favorite wife of Emperor Shah Jahan, this most beautiful of mausoleums was begun upon her death in 1631 and took 20,000 workmen until 1648 to complete.\r\n\r\nIncorporating many elements of Islamic design including arches, minarets, an onion-shaped dome, and black calligraphy inlaid around the entrance, the Taj Mahal is largely constructed of white marble decorated with delicate inlaid floral patterns and precious and semi-precious stones such as jade, lapis lazuli, diamonds, and mother of pearl.', 3, 1, '2021-08-25 11:14:10'),
(11, 'travel11.jpg', 'varanashi', 'banarsha', 'A major pilgrimage center for Hindus, the holy city of Varanasi has long been associated with the mighty Ganges River, one of the faith\'s most important religious symbols. Dating back to the 8th century BC, Varanasi is one of the oldest still inhabited cities in the world.\r\n\r\nIt offers many reasons to visit, not least of them the chance to explore the Old Quarter adjacent to the Ganges where you\'ll find the Kashi Vishwanath Temple, built in 1780 (the New Vishwanath Temple with its seven separate temples is also of interest).\r\n\r\nBathing in the Ganges is of great importance to Hindus, and numerous locations known as \"ghats\" feature stairways leading to the water where the faithful bathe before prayers.', 4, 1, '2021-08-25 11:14:10'),
(12, 'travel12.jpg', 'Khaanaha national park', 'Mandla', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 2, 0, '2021-08-26 15:59:15'),
(13, 'travel13.png', 'Hawa mahal', 'jaipur', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 3, 0, '2021-08-26 15:59:15'),
(14, 'travel14.jpg', 'Mumbai Gate', 'Mumbai', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 3, 0, '2021-08-26 16:04:38'),
(15, 'travel15.jpg', 'Qutub minar', 'Delhi', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 3, 0, '2021-08-26 16:04:38'),
(16, 'travel16.jpg', 'statue of unity', 'Gujarate', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 3, 0, '2021-08-26 16:04:38'),
(17, 'travel17.jpg', 'Fight Home', 'Londom ', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 1, 0, '2021-08-26 16:11:34'),
(18, 'travel18.jpg', 'peramit', 'Egypet', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 2, 0, '2021-08-26 16:11:34'),
(19, 'travel19.jpg', 'Ifill Tower', 'Tokyo', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 3, 0, '2021-08-26 16:11:34'),
(20, 'travel20.jpg', 'China wall', 'China', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 1, 0, '2021-08-26 16:11:34'),
(21, 'travel21.jpg', 'Londan ghate', 'London', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 4, 0, '2021-08-26 16:11:34'),
(22, 'travel22.jpg', 'Night Club', 'New York', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 1, 0, '2021-08-26 16:11:34'),
(23, 'travel23.jpg', 'Beautyful', 'Swizerland', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 2, 0, '2021-08-26 16:11:34'),
(24, 'travel24.jpg', 'Statue of Beauty', 'Brazil', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 3, 0, '2021-08-26 16:11:34'),
(25, 'travel25.jpg', 'Burj Khalifa', 'arab', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 4, 0, '2021-08-27 06:47:49'),
(26, 'travel26.jpg', 'africa national park', 'Africa', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 2, 0, '2021-08-27 06:47:49'),
(27, 'travel27.png', 'Yellow home', 'China', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 3, 0, '2021-08-27 06:47:49'),
(28, 'travel28.jpg', 'Tupi', 'karishma', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 1, 0, '2021-08-27 06:47:49'),
(29, 'travel29.jpg', 'Everest', 'Karishma', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 3, 0, '2021-08-27 06:47:49'),
(30, 'travel30.jpg', 'Babar', 'Pakistan', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 2, 0, '2021-08-27 06:47:49'),
(31, 'travel31.jpg', 'Himachal', 'Himachal', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 3, 0, '2021-08-27 06:47:49'),
(32, 'travel32.jpg', 'Ravi mahal', 'Chttisgrad', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 2, 0, '2021-08-27 06:47:49'),
(33, 'travel33.jpg', 'mountail', 'Rajesthan', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 1, 0, '2021-08-27 06:47:49'),
(34, 'travel34.jpg', 'Beach boat', 'Kerala', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 4, 0, '2021-08-27 06:47:49'),
(35, 'travel35.jpg', 'Beach goa', 'Goa', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 2, 0, '2021-08-27 06:47:49'),
(36, 'travel36.jpg', 'jaannat', 'Lakshadeep', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 3, 0, '2021-08-27 06:47:49'),
(37, 'travel37.jpg', 'sharda temple', 'mahair', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 4, 0, '2021-08-27 06:47:49'),
(38, 'travel38.jpg', 'bhada ghat', 'jabalpur', 'Chhatrapati Shivaji Terminus, is a historic terminal train station and UNESCO World Heritage Site in Mumbai, Maharashtra, India. The terminus was designed by British born architectural engineer Frederick William Stevens from an initial design by Axel Haig, in an exuberant Italian Gothic style. Its construction began in 1878, in a location south of the old Bori Bunder railway station, and was completed in 1887, the year marking 50 years of Queen Victoria\'s rule. In March 1996 the station\'s name was changed to \"Chhatrapati Shivaji Terminus\" after Shivaji, the 17th-century warrior king who employed guerrilla tactics to contest the declining Mughal Empire and found a new state in the western Marathi-speaking regions of the Deccan Plateau. During the 18th-century the state was expanded by the Peshwas to extend over many interior regions of India as the Maratha Confederacy, or the Maratha Empire. The expansion was checked in 1761 by the Afghans in the Third Battle of Panipat, and the empire defeated by the British in 1817–18 in the Third Anglo-Maratha War. Wikipedia', 3, 0, '2021-08-27 06:47:49'),
(39, 'travel39.jpg', 'bhae', 'bhutan', 'Himachal', 3, 0, '2021-08-27 07:16:57'),
(40, 'travel40.jpg', 'Jaldapara National Park Pron ld p r is a national park situated at the foothills of the Eastern Hima', 'delhi', 'Jaldapara National Park Pron ld p r is a national park situated at the foothills of the Eastern Himalayas in Alipurduar District of northern West Bengal and on the banks...', 3, 0, '2021-08-27 07:16:57');

-- --------------------------------------------------------

--
-- Table structure for table `subscriber`
--

CREATE TABLE `subscriber` (
  `id` int(11) NOT NULL,
  `username` varchar(244) NOT NULL,
  `email` varchar(244) NOT NULL,
  `password` varchar(244) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `subscriber`
--

INSERT INTO `subscriber` (`id`, `username`, `email`, `password`) VALUES
(1, 'kapil', 'kapildev20@gmail.com', 'kapil'),
(3, 'anam_1', 'anamansari20@gmail.com', 'anam'),
(4, 'archana', 'archana20@gmail.com', 'archana');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `comments`
--
ALTER TABLE `comments`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `contents`
--
ALTER TABLE `contents`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `subscriber`
--
ALTER TABLE `subscriber`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `comments`
--
ALTER TABLE `comments`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=199;

--
-- AUTO_INCREMENT for table `contents`
--
ALTER TABLE `contents`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=41;

--
-- AUTO_INCREMENT for table `subscriber`
--
ALTER TABLE `subscriber`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
